services:
  server:
    build:
      context: ./
    ports:
      - 80:80
      - 5173:5173
    volumes:
      - ./:/var/www/ams
      - /var/www/ams/vendor
    depends_on:
      - db
  db:
    image: mysql:8.4
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      TZ: "UTC"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
volumes:
  db:
    driver: local
